/*
 * Copyright (C), 2014-2015, 杭州小卡科技有限公司
 * FileName: FixerDevice.java
 * Author: mbg
 * Date: 2016年01月30日 下午 01:48:31
 * Description:
 */
package com.wetrack.ikongtiao.domain;

import java.io.Serializable;

public class FixerDevice implements Serializable {
    /**
     * id:
     */
    private Integer id;

    /**
     * fixer_id:
     */
    private Integer fixerId;

    /**
     * os_type:系统标识，android or ios
     */
    private String osType;

    /**
     * os_version:系统版本
     */
    private String osVersion;

    /**
     * device_type:手机型号
     */
    private String deviceType;

    /**
     * client_id:个推push clientId
     */
    private String clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fixer_device
     *
     * @mbggenerated Sat Jan 30 13:48:31 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of fixer_id
     */
    public Integer getFixerId() {
        return fixerId;
    }

    /**
     * @param fixerId the value for fixer_id
     */
    public void setFixerId(Integer fixerId) {
        this.fixerId = fixerId;
    }

    /**
     * @return the value of os_type
     */
    public String getOsType() {
        return osType;
    }

    /**
     * @param osType the value for os_type
     */
    public void setOsType(String osType) {
        this.osType = osType == null ? null : osType.trim();
    }

    /**
     * @return the value of os_version
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * @param osVersion the value for os_version
     */
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion == null ? null : osVersion.trim();
    }

    /**
     * @return the value of device_type
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * @param deviceType the value for device_type
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * @return the value of client_id
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * @param clientId the value for client_id
     */
    public void setClientId(String clientId) {
        this.clientId = clientId == null ? null : clientId.trim();
    }

    /**
     * This method corresponds to the database table fixer_device
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fixerId=").append(fixerId);
        sb.append(", osType=").append(osType);
        sb.append(", osVersion=").append(osVersion);
        sb.append(", deviceType=").append(deviceType);
        sb.append(", clientId=").append(clientId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}