/*
 * Copyright (C), 2014-2015, 杭州小卡科技有限公司
 * FileName: ImMessage.java
 * Author: mbg
 * Date: 2016年03月17日 下午 11:23:55
 * Description:
 */
package com.wetrack.ikongtiao.domain;

import java.io.Serializable;
import java.util.Date;

public class ImMessage implements Serializable {
    /**
     * id:
     */
    private Long id;

    /**
     * session_id:会话id
     */
    private Integer sessionId;

    /**
     * message_uid:消息全局唯一id
     */
    private String messageUid;

    /**
     * message_to:消息发送对象
     */
    private String messageTo;

    /**
     * message_from:消息来源
     */
    private String messageFrom;

    /**
     * message_type:消息类型，0文字，1，图片
     */
    private Integer messageType;

    /**
     * message_group_type:消息分组类型，0：客服和微信之间，1:客服和维修员之间；2:维修员和微信之间
     */
    private Integer messageGroupType;

    /**
     * create_time:
     */
    private Date createTime;

    /**
     * message_content:消息内容或者图片url
     */
    private String messageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table im_message1
     *
     * @mbggenerated Thu Mar 17 23:23:55 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the value of session_id
     */
    public Integer getSessionId() {
        return sessionId;
    }

    /**
     * @param sessionId the value for session_id
     */
    public void setSessionId(Integer sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * @return the value of message_uid
     */
    public String getMessageUid() {
        return messageUid;
    }

    /**
     * @param messageUid the value for message_uid
     */
    public void setMessageUid(String messageUid) {
        this.messageUid = messageUid == null ? null : messageUid.trim();
    }

    /**
     * @return the value of message_to
     */
    public String getMessageTo() {
        return messageTo;
    }

    /**
     * @param messageTo the value for message_to
     */
    public void setMessageTo(String messageTo) {
        this.messageTo = messageTo == null ? null : messageTo.trim();
    }

    /**
     * @return the value of message_from
     */
    public String getMessageFrom() {
        return messageFrom;
    }

    /**
     * @param messageFrom the value for message_from
     */
    public void setMessageFrom(String messageFrom) {
        this.messageFrom = messageFrom == null ? null : messageFrom.trim();
    }

    /**
     * @return the value of message_type
     */
    public Integer getMessageType() {
        return messageType;
    }

    /**
     * @param messageType the value for message_type
     */
    public void setMessageType(Integer messageType) {
        this.messageType = messageType;
    }

    /**
     * @return the value of message_group_type
     */
    public Integer getMessageGroupType() {
        return messageGroupType;
    }

    /**
     * @param messageGroupType the value for message_group_type
     */
    public void setMessageGroupType(Integer messageGroupType) {
        this.messageGroupType = messageGroupType;
    }

    /**
     * @return the value of create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the value for create_time
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return the value of message_content
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * @param messageContent the value for message_content
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }

    /**
     * This method corresponds to the database table im_message1
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sessionId=").append(sessionId);
        sb.append(", messageUid=").append(messageUid);
        sb.append(", messageTo=").append(messageTo);
        sb.append(", messageFrom=").append(messageFrom);
        sb.append(", messageType=").append(messageType);
        sb.append(", messageGroupType=").append(messageGroupType);
        sb.append(", createTime=").append(createTime);
        sb.append(", messageContent=").append(messageContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}