/*
 * Copyright (C), 2014-2015, 杭州小卡科技有限公司
 * FileName: ImMessage.java
 * Author: mbg
 * Date: 2016年02月27日 下午 02:58:57
 * Description:
 */
package com.wetrack.ikongtiao.domain;

import java.io.Serializable;
import java.util.Date;

public class ImMessage implements Serializable {
	/**
	 * id:
	 */
	private Long id;

	/**
	 * message_to:
	 */
	private String messageTo;

	/**
	 * message_from:
	 */
	private String messageFrom;

	/**
	 * message_content，文字类型的消息为文字内容:，图片类型的，存储的是图片的地址
	 */
	private String messageContent;

	/**
	 * 消息类型，0，文字，1图片，
	 */
	private Integer messageType;

	/**
	 * create_time:
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database table im_message
	 *
	 * @mbggenerated Sat Feb 27 14:58:57 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * @return the value of id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the value for id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the value of message_to
	 */
	public String getMessageTo() {
		return messageTo;
	}

	/**
	 * @param messageTo the value for message_to
	 */
	public void setMessageTo(String messageTo) {
		this.messageTo = messageTo == null ? null : messageTo.trim();
	}

	/**
	 * @return the value of message_from
	 */
	public String getMessageFrom() {
		return messageFrom;
	}

	/**
	 * @param messageFrom the value for message_from
	 */
	public void setMessageFrom(String messageFrom) {
		this.messageFrom = messageFrom == null ? null : messageFrom.trim();
	}

	/**
	 * @return the value of message_content
	 */
	public String getMessageContent() {
		return messageContent;
	}

	/**
	 * @param messageContent the value for message_content
	 */
	public void setMessageContent(String messageContent) {
		this.messageContent = messageContent == null ? null : messageContent.trim();
	}

	/**
	 * @return the value of create_time
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime the value for create_time
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Integer getMessageType() {
		return messageType;
	}

	public void setMessageType(Integer messageType) {
		this.messageType = messageType;
	}

	/**
	 * This method corresponds to the database table im_message
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", messageTo=").append(messageTo);
		sb.append(", messageFrom=").append(messageFrom);
		sb.append(", messageContent=").append(messageContent);
		sb.append(", createTime=").append(createTime);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}