/*
 * Copyright (C), 2014-2015, 杭州小卡科技有限公司
 * FileName: ImToken.java
 * Author: mbg
 * Date: 2016年03月17日 下午 11:23:55
 * Description:
 */
package com.wetrack.ikongtiao.domain;

import java.io.Serializable;
import java.util.Date;

public class ImToken implements Serializable {
    /**
     * id:
     */
    private Integer id;

    /**
     * cloud_id:融云id
     */
    private String cloudId;

    /**
     * system_id:系统用户体系id
     */
    private String systemId;

    /**
     * role_type:用户类型：0:微信用户；1:客服；2:维修员
     */
    private Integer roleType;

    /**
     * avator:用户头像
     */
    private String avator;

    /**
     * tag:用户标签（用户名）
     */
    private String tag;

    /**
     * cloud_token:该用户在融云对应的token
     */
    private String cloudToken;

    /**
     * create_time:
     */
    private Date createTime;

    /**
     * update_time:
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table im_token1
     *
     * @mbggenerated Thu Mar 17 23:23:55 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of cloud_id
     */
    public String getCloudId() {
        return cloudId;
    }

    /**
     * @param cloudId the value for cloud_id
     */
    public void setCloudId(String cloudId) {
        this.cloudId = cloudId == null ? null : cloudId.trim();
    }

    /**
     * @return the value of system_id
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * @param systemId the value for system_id
     */
    public void setSystemId(String systemId) {
        this.systemId = systemId == null ? null : systemId.trim();
    }

    /**
     * @return the value of role_type
     */
    public Integer getRoleType() {
        return roleType;
    }

    /**
     * @param roleType the value for role_type
     */
    public void setRoleType(Integer roleType) {
        this.roleType = roleType;
    }

    /**
     * @return the value of avator
     */
    public String getAvator() {
        return avator;
    }

    /**
     * @param avator the value for avator
     */
    public void setAvator(String avator) {
        this.avator = avator == null ? null : avator.trim();
    }

    /**
     * @return the value of tag
     */
    public String getTag() {
        return tag;
    }

    /**
     * @param tag the value for tag
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * @return the value of cloud_token
     */
    public String getCloudToken() {
        return cloudToken;
    }

    /**
     * @param cloudToken the value for cloud_token
     */
    public void setCloudToken(String cloudToken) {
        this.cloudToken = cloudToken == null ? null : cloudToken.trim();
    }

    /**
     * @return the value of create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the value for create_time
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return the value of update_time
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * @param updateTime the value for update_time
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method corresponds to the database table im_token1
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cloudId=").append(cloudId);
        sb.append(", systemId=").append(systemId);
        sb.append(", roleType=").append(roleType);
        sb.append(", avator=").append(avator);
        sb.append(", tag=").append(tag);
        sb.append(", cloudToken=").append(cloudToken);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}