/*
 * Copyright (C), 2014-2015, xiazhou
 * FileName: MachineType.java
 * Author: xiazhou
 * Date: 2015年12月13日 下午 06:04:56
 * Description:
 */
package com.wetrack.ikongtiao.domain;

import java.io.Serializable;

public class MachineType implements Serializable {
    /**
     * id:
     */
    private Integer id;

    /**
     * 父类id
     */
    private Integer parentId;

    /**
     * name:机器名字
     */
    private String name;

    /**
     * img:机器图片地址
     */
    private String img;

    /**
     * remark:机器描述
     */
    private String remark;

    /**
     * is_valid:对应值是否可用：0-禁用,1-可用
     */
    private Byte isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table machine_type
     *
     * @xiazhougenerated Sun Dec 13 18:04:56 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * @return the value of name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the value for name
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * @return the value of img
     */
    public String getImg() {
        return img;
    }

    /**
     * @param img the value for img
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the value of is_valid
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * @param isValid the value for is_valid
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method corresponds to the database table machine_type
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", img=").append(img);
        sb.append(", remark=").append(remark);
        sb.append(", isValid=").append(isValid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}