/*
 * Copyright (C), 2014-2015, xiazhou
 * FileName: MicroCode.java
 * Author: xiazhou
 * Date: 2015年12月10日 下午 10:25:26
 * Description:
 */
package com.wetrack.ikongtiao.domain;

import java.io.Serializable;

public class MicroCode implements Serializable {
    /**
     * id:
     */
    private Integer id;

    /**
     * code:代码值
     */
    private String code;

    /**
     * key:对应名称
     */
    private String key;

    /**
     * value:对应值
     */
    private String value;

    /**
     * is_valid:对应值是否可用：0-禁用,1-可用
     */
    private Byte isValid;

    /**
     * remark:对应值备注
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table micro_code
     *
     * @xiazhougenerated Thu Dec 10 22:25:26 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of code
     */
    public String getCode() {
        return code;
    }

    /**
     * @param code the value for code
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * @return the value of key
     */
    public String getKey() {
        return key;
    }

    /**
     * @param key the value for key
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * @return the value of value
     */
    public String getValue() {
        return value;
    }

    /**
     * @param value the value for value
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * @return the value of is_valid
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * @param isValid the value for is_valid
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * @return the value of remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the value for remark
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method corresponds to the database table micro_code
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", key=").append(key);
        sb.append(", value=").append(value);
        sb.append(", isValid=").append(isValid);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}