/*
 * Copyright (C), 2014-2015, xiazhou
 * FileName: Mission.java
 * Author: xiazhou
 * Date: 2015年12月15日 下午 00:50:23
 * Description:
 */
package com.wetrack.ikongtiao.domain;

import java.io.Serializable;
import java.util.Date;

public class Mission implements Serializable {
    /**
     * id:
     */
    private Integer id;

    /**
     * user_id:用户Id
     */
    private String userId;

    /**
     * machine_type_id:机器类型id
     */
    private Integer machineTypeId;

    /**
     * mission_desc:任务描述
     */
    private String missionDesc;

    /**
     * mission_state:任务状态:0-新任务,1-已受理,2-诊断中,3-维修中, -1 -已关闭 10 已完成
     */
    private Integer missionState;

    /**
     * is_need_more:是否需要详细信息:0-不需要,1-需要
     */
    private Integer isNeedMore;

    /**
     * fixer_id:维修人id
     */
    private Integer fixerId;

    /**
     * admin_user_id:客服id
     */
    private Integer adminUserId;

    /**
     * mission_address_id:任务地址id
     */
    private Integer missionAddressId;

    /**
     * operator:操作人
     */
    @Deprecated
    private String operator;

    /**
     * create_time:
     */
    private Date createTime;

    /**
     * update_time:
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mission
     *
     * @xiazhougenerated Tue Dec 15 12:50:23 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of user_id
     */
    public String getUserId() {
        return userId;
    }

    /**
     * @param userId the value for user_id
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    public Integer getMachineTypeId() {
        return machineTypeId;
    }

    public void setMachineTypeId(Integer machineTypeId) {
        this.machineTypeId = machineTypeId;
    }

    /**
     * @return the value of mission_desc
     */
    public String getMissionDesc() {
        return missionDesc;
    }

    /**
     * @param missionDesc the value for mission_desc
     */
    public void setMissionDesc(String missionDesc) {
        this.missionDesc = missionDesc == null ? null : missionDesc.trim();
    }

    public Integer getMissionState() {
        return missionState;
    }

    public void setMissionState(Integer missionState) {
        this.missionState = missionState;
    }

    public Integer getIsNeedMore() {
        return isNeedMore;
    }

    public void setIsNeedMore(Integer isNeedMore) {
        this.isNeedMore = isNeedMore;
    }

    /**
     * @return the value of fixer_id
     */
    public Integer getFixerId() {
        return fixerId;
    }

    /**
     * @param fixerId the value for fixer_id
     */
    public void setFixerId(Integer fixerId) {
        this.fixerId = fixerId;
    }

    /**
     * @return the value of admin_user_id
     */
    public Integer getAdminUserId() {
        return adminUserId;
    }

    /**
     * @param adminUserId the value for admin_user_id
     */
    public void setAdminUserId(Integer adminUserId) {
        this.adminUserId = adminUserId;
    }

    /**
     * @return the value of mission_address_id
     */
    public Integer getMissionAddressId() {
        return missionAddressId;
    }

    /**
     * @param missionAddressId the value for mission_address_id
     */
    public void setMissionAddressId(Integer missionAddressId) {
        this.missionAddressId = missionAddressId;
    }

    /**
     * @return the value of operator
     */
    public String getOperator() {
        return operator;
    }

    /**
     * @param operator the value for operator
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * @return the value of create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the value for create_time
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return the value of update_time
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * @param updateTime the value for update_time
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}