/*
 * Copyright (C), 2014-2015, xiazhou
 * FileName: PaymentInfo.java
 * Author: xiazhou
 * Date: 2015年12月15日 下午 00:50:23
 * Description:
 */
package com.wetrack.ikongtiao.domain;

import java.io.Serializable;
import java.util.Date;

public class PaymentInfo implements Serializable {
    /**
     * id:
     */
    private Integer id;

    /**
     * payment_method:支付方式:0-线下,1-微信
     */
    private Byte paymentMethod;

    /**
     * repair_order_id:维修单id
     */
    private Integer repairOrderId;

    /**
     * out_trade_no:外部交易号:和支付系统交互
     */
    private Long outTradeNo;

    /**
     * trade_no:交易号:支付系统唯一ID
     */
    private String tradeNo;

    /**
     * pay_state:支付状态:0-待支付,1-已支付,2-部分退款,3-全部退款,4-已关闭
     */
    private Byte payState;

    /**
     * pay_amount:支付金额 单位为分
     */
    private Integer payAmount;

    /**
     * refund_amount:退款金额 单位为分
     */
    private Integer refundAmount;

    /**
     * paid_time:支付时间
     */
    private Date paidTime;

    /**
     * refund_time:退款时间
     */
    private Date refundTime;

    /**
     * repair_order_desc:维修单描述
     */
    private String repairOrderDesc;

    /**
     * operator:操作人
     */
    private String operator;

    /**
     * create_time:
     */
    private Date createTime;

    /**
     * update_time:
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_info
     *
     * @xiazhougenerated Tue Dec 15 12:50:23 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of payment_method
     */
    public Byte getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * @param paymentMethod the value for payment_method
     */
    public void setPaymentMethod(Byte paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * @return the value of repair_order_id
     */
    public Integer getRepairOrderId() {
        return repairOrderId;
    }

    /**
     * @param repairOrderId the value for repair_order_id
     */
    public void setRepairOrderId(Integer repairOrderId) {
        this.repairOrderId = repairOrderId;
    }

    /**
     * @return the value of out_trade_no
     */
    public Long getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * @param outTradeNo the value for out_trade_no
     */
    public void setOutTradeNo(Long outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    /**
     * @return the value of trade_no
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * @param tradeNo the value for trade_no
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * @return the value of pay_state
     */
    public Byte getPayState() {
        return payState;
    }

    /**
     * @param payState the value for pay_state
     */
    public void setPayState(Byte payState) {
        this.payState = payState;
    }

    /**
     * @return the value of pay_amount
     */
    public Integer getPayAmount() {
        return payAmount;
    }

    /**
     * @param payAmount the value for pay_amount
     */
    public void setPayAmount(Integer payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * @return the value of refund_amount
     */
    public Integer getRefundAmount() {
        return refundAmount;
    }

    /**
     * @param refundAmount the value for refund_amount
     */
    public void setRefundAmount(Integer refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * @return the value of paid_time
     */
    public Date getPaidTime() {
        return paidTime;
    }

    /**
     * @param paidTime the value for paid_time
     */
    public void setPaidTime(Date paidTime) {
        this.paidTime = paidTime;
    }

    /**
     * @return the value of refund_time
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * @param refundTime the value for refund_time
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * @return the value of repair_order_desc
     */
    public String getRepairOrderDesc() {
        return repairOrderDesc;
    }

    /**
     * @param repairOrderDesc the value for repair_order_desc
     */
    public void setRepairOrderDesc(String repairOrderDesc) {
        this.repairOrderDesc = repairOrderDesc == null ? null : repairOrderDesc.trim();
    }

    /**
     * @return the value of operator
     */
    public String getOperator() {
        return operator;
    }

    /**
     * @param operator the value for operator
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * @return the value of create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the value for create_time
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return the value of update_time
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * @param updateTime the value for update_time
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method corresponds to the database table payment_info
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", paymentMethod=").append(paymentMethod);
        sb.append(", repairOrderId=").append(repairOrderId);
        sb.append(", outTradeNo=").append(outTradeNo);
        sb.append(", tradeNo=").append(tradeNo);
        sb.append(", payState=").append(payState);
        sb.append(", payAmount=").append(payAmount);
        sb.append(", refundAmount=").append(refundAmount);
        sb.append(", paidTime=").append(paidTime);
        sb.append(", refundTime=").append(refundTime);
        sb.append(", repairOrderDesc=").append(repairOrderDesc);
        sb.append(", operator=").append(operator);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}