/*
 * Copyright (C), 2014-2015, xiazhou
 * FileName: PaymentInfo.java
 * Author: xiazhou
 * Date: 2015年12月15日 下午 00:50:23
 * Description:
 */
package com.wetrack.ikongtiao.domain;

import java.io.Serializable;
import java.util.Date;

public class PaymentInfo implements Serializable {
    /**
     * id:
     */
    private Long id;

    /**
     * payment_method:支付方式:1-微信
     */
    private Byte paymentMethod;

    /**
     * out_trade_no:外部交易号:和支付系统交互
     */
    private String outTradeNo;

    /**
     * pay_state:支付状态:0-待支付,1-已支付,2-部分退款,3-全部退款,4-已关闭
     */
    private Byte payState;

    /**
     * pay_amount:支付金额 单位为分
     */
    private Integer payAmount;

    /**
     * refund_amount:退款金额 单位为分
     */
    private Integer refundAmount;

    /**
     * paid_time:支付时间
     */
    private Date paidTime;

    /**
     * refund_time:退款时间
     */
    private Date refundTime;
    /**
     * create_time:
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_info
     *
     * @xiazhougenerated Tue Dec 15 12:50:23 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for id
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the value of payment_method
     */
    public Byte getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * @param paymentMethod the value for payment_method
     */
    public void setPaymentMethod(Byte paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * @return the value of out_trade_no
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * @param outTradeNo the value for out_trade_no
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    /**
     * @return the value of pay_state
     */
    public Byte getPayState() {
        return payState;
    }

    /**
     * @param payState the value for pay_state
     */
    public void setPayState(Byte payState) {
        this.payState = payState;
    }

    /**
     * @return the value of pay_amount
     */
    public Integer getPayAmount() {
        return payAmount;
    }

    /**
     * @param payAmount the value for pay_amount
     */
    public void setPayAmount(Integer payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * @return the value of refund_amount
     */
    public Integer getRefundAmount() {
        return refundAmount;
    }

    /**
     * @param refundAmount the value for refund_amount
     */
    public void setRefundAmount(Integer refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * @return the value of paid_time
     */
    public Date getPaidTime() {
        return paidTime;
    }

    /**
     * @param paidTime the value for paid_time
     */
    public void setPaidTime(Date paidTime) {
        this.paidTime = paidTime;
    }

    /**
     * @return the value of refund_time
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * @param refundTime the value for refund_time
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * @return the value of create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the value for create_time
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method corresponds to the database table payment_info
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", paymentMethod=").append(paymentMethod);
        sb.append(", outTradeNo=").append(outTradeNo);
        sb.append(", payState=").append(payState);
        sb.append(", payAmount=").append(payAmount);
        sb.append(", refundAmount=").append(refundAmount);
        sb.append(", paidTime=").append(paidTime);
        sb.append(", refundTime=").append(refundTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public enum State{
        WAIT(0),
        PAID(1),
        PART_REFUND(2),
        TOTAL_REFUND(3),
        CLOSED(4),
        PAID_ERROR(-1),
        ;

        int code;

        State(int code){
            this.code = code;
        }

        public int getCode(){
            return code;
        }
    }

    public enum Method{
        WECHAT(1),
        ;

        int code;

        Method(int code){
            this.code = code;
        }

        public int getCode(){
            return code;
        }
    }

    public enum Type{
        RO(1), //维修单repair_order
        ;

        int code;

        Type(int code){
            this.code = code;
        }

        public int getCode(){
            return code;
        }
    }
}