/*
 * Copyright (C), 2014-2015, xiazhou
 * FileName: PaymentInfo.java
 * Author: xiazhou
 * Date: 2015年12月15日 下午 00:50:23
 * Description:
 */
package com.wetrack.ikongtiao.domain;

import java.io.Serializable;
import java.util.Date;

public class PaymentInfo implements Serializable {
    /**
     * id:
     */
    private Long id;

    /**
     * method:支付方式:1-微信
     */
    private Method method;

    /**
     * out_trade_no:外部交易号:和支付系统交互
     */
    private String outTradeNo;

    /**
     * state:支付状态
     */
    private State state;

    /**
     * amount:支付金额 单位为分
     */
    private Integer amount;

    /**
     * refund_amount:退款金额 单位为分
     */
    private Integer refundAmount;

    /**
     * paid_time:支付时间
     */
    private Date paidTime;

    /**
     * refund_time:退款时间
     */
    private Date refundTime;
    /**
     * create_time:
     */
    private Date createTime;
    /**
     * close_time:
     */
    private Date closeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table payment_info
     *
     * @xiazhougenerated Tue Dec 15 12:50:23 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the value for id
     */
    public void setId(Long id) {
        this.id = id;
    }


    /**
     * @return the value of out_trade_no
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * @param outTradeNo the value for out_trade_no
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    /**
     * @return the value of refund_amount
     */
    public Integer getRefundAmount() {
        return refundAmount;
    }

    /**
     * @param refundAmount the value for refund_amount
     */
    public void setRefundAmount(Integer refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * @return the value of paid_time
     */
    public Date getPaidTime() {
        return paidTime;
    }

    /**
     * @param paidTime the value for paid_time
     */
    public void setPaidTime(Date paidTime) {
        this.paidTime = paidTime;
    }

    /**
     * @return the value of refund_time
     */
    public Date getRefundTime() {
        return refundTime;
    }

    /**
     * @param refundTime the value for refund_time
     */
    public void setRefundTime(Date refundTime) {
        this.refundTime = refundTime;
    }

    /**
     * @return the value of create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the value for create_time
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Method getMethod() {
        return method;
    }

    public void setMethod(Method method) {
        this.method = method;
    }

    public State getState() {
        return state;
    }

    public void setState(State state) {
        this.state = state;
    }

    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public Date getCloseTime() {
        return closeTime;
    }

    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method corresponds to the database table payment_info
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", method=").append(method);
        sb.append(", amount=").append(amount);
        sb.append(", state=").append(state);
        sb.append(", outTradeNo=").append(outTradeNo);
        sb.append(", refundAmount=").append(refundAmount);
        sb.append(", paidTime=").append(paidTime);
        sb.append(", refundTime=").append(refundTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     *
     * SUCCESS—支付成功
     * REFUND—转入退款
     * NOTPAY—未支付
     * CLOSED—已关闭
     * REVOKED—已撤销（刷卡支付）
     * USERPAYING--用户支付中
     * PAYERROR--支付失败(其他原因，如银行返回失败)
     *
     */
    public enum State{
        NOTPAY,
        SUCCESS,
        REFUND,
        CLOSED,
        REVOKED,
        USERPAYING,
        PAYERROR;
    }

    public enum Method{
        WECHAT,
        ;

    }

    public enum Type{
        RO, //维修单repair_order
        ;
    }

    public static void main(String[] args){
        System.out.println(Method.WECHAT.toString());
    }
}