/*
 * Copyright (C), 2014-2015, xiazhou
 * FileName: SystemParam.java
 * Author: xiazhou
 * Date: 2015年12月10日 下午 10:25:26
 * Description:
 */
package com.wetrack.ikongtiao.domain;

import java.io.Serializable;

public class SystemParam implements Serializable {
    /**
     * key:键
     */
    private String key;

    /**
     * value:值
     */
    private String value;

    /**
     * remark:备注
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_param
     *
     * @xiazhougenerated Thu Dec 10 22:25:26 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of key
     */
    public String getKey() {
        return key;
    }

    /**
     * @param key the value for key
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * @return the value of value
     */
    public String getValue() {
        return value;
    }

    /**
     * @param value the value for value
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * @return the value of remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the value for remark
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method corresponds to the database table system_param
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", key=").append(key);
        sb.append(", value=").append(value);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}