/*
 * Copyright (C), 2014-2015, xiazhou
 * FileName: MachineType.java
 * Author: xiazhou
 * Date: 2015年12月13日 下午 06:04:56
 * Description:
 */
package com.wetrack.ikongtiao.domain.machine;

import lombok.Data;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import java.io.Serializable;

@Entity(name = "machine_type")
@Data
public class MachineType implements Serializable {
    /**
     * id:
     */
    @javax.persistence.Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * 型号
     */
    private String name;

    /**
     * img:机器图片地址
     */
    private String img;

    /**
     * remark:机器描述
     */
    private String remark;
    /**
     * 所属机种
     */
    @Column(name = "machine_model_id")
    private Long machineModelId;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table machine_type
     *
     * @xiazhougenerated Sun Dec 13 18:04:56 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method corresponds to the database table machine_type
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", img=").append(img);
        sb.append(", remark=").append(remark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}